version: 2
jobs:
  first:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "The first job is running..."
      - run: sleep 25
  second:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "The second job is running..."
      - run: sleep 15
workflows:
  version: 2
  first_and_second:
    jobs:
      - first
      - second
